In [2]:
import pandas as pd
import scipy.stats as stats
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.externals.six import StringIO
import glob
import os
import numpy as np

#visualization
%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import Image
import pydot

/Users/zlatakobzantsev/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [10]:
pluto_mn = pd.read_csv("../data/pluto/MN.csv")
pluto_bx = pd.read_csv("../data/pluto/BX.csv")
pluto_bk = pd.read_csv("../data/pluto/BK.csv")
pluto_qn = pd.read_csv("../data/pluto/QN.csv")
pluto_si = pd.read_csv("../data/pluto/SI.csv")
print pluto_mn.head()
pluto_mn.dtypes

  Borough  Block  Lot   CD  CT2010  CB2010  SchoolDist  Council  ZipCode  \
0      MN      1   10  101     5.0  1018.0         2.0      1.0  10004.0
1      MN      1  101  101     1.0  1001.0         2.0      1.0  10004.0
2      MN      1  201  101     1.0  1000.0         2.0      1.0  10004.0
3      MN      1  301  101     NaN     NaN         2.0      1.0  10004.0
4      MN      1  401  101     NaN     NaN         2.0      1.0  10004.0

  FireComp   ...      YCoord  ZoneMap  ZMCode   Sanborn   TaxMap EDesigNum  \
0     E007   ...    190225.0      16a       Y   199 999  10101.0       NaN
1     E007   ...    190636.0      16a       Y   199 999  10101.0       NaN
2     E007   ...    193648.0      12b     NaN   199 999  10101.0       NaN
3     E007   ...         NaN      12b     NaN   199 999  10101.0       NaN
4     E007   ...         NaN      12b     NaN  1 99 999  10101.0       NaN

  APPBBL APPDate PLUTOMapID Version
0    0.0     NaN          1    16v1
1    0.0     NaN          1    16v1
2    0.0     NaN          1    16v1
3    0.0     NaN          4    16v1
4    0.0     NaN          4    16v1

[5 rows x 86 columns]
Borough           object
Block              int64
Lot                int64
CD                 int64
CT2010           float64
CB2010           float64
SchoolDist       float64
Council          float64
ZipCode          float64
FireComp          object
PolicePrct       float64
HealthArea       float64
SanitBoro        float64
SanitDistrict    float64
SanitSub          object
Address           object
ZoneDist1         object
ZoneDist2         object
ZoneDist3         object
ZoneDist4         object
Overlay1          object
Overlay2          object
SPDist1           object
SPDist2           object
LtdHeight         object
AllZoning1        object
AllZoning2        object
SplitZone         object
BldgClass         object
LandUse          float64
                  ...
BsmtCode         float64
AssessLand         int64
AssessTot          int64
ExemptLand         int64
ExemptTot          int64
YearBuilt          int64
BuiltCode         object
YearAlter1         int64
YearAlter2         int64
HistDist          object
Landmark          object
BuiltFAR         float64
ResidFAR         float64
CommFAR          float64
FacilFAR         float64
BoroCode           int64
BBL                int64
CondoNo            int64
Tract2010          int64
XCoord           float64
YCoord           float64
ZoneMap           object
ZMCode            object
Sanborn           object
TaxMap           float64
EDesigNum         object
APPBBL           float64
APPDate           object
PLUTOMapID         int64
Version           object
dtype: object

In [11]:
frames = [pluto_mn, pluto_bx, pluto_bk, pluto_qn, pluto_si]

In [12]:
pluto_nyc = pd.concat(frames)

In [13]:
pluto_nyc.head()

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,YCoord,ZoneMap,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,Version
0,MN,1,10,101,5.0,1018.0,2.0,1.0,10004.0,E007,...,190225.0,16a,Y,199 999,10101.0,NaN,0.0,NaN,1,16v1
1,MN,1,101,101,1.0,1001.0,2.0,1.0,10004.0,E007,...,190636.0,16a,Y,199 999,10101.0,NaN,0.0,NaN,1,16v1
2,MN,1,201,101,1.0,1000.0,2.0,1.0,10004.0,E007,...,193648.0,12b,NaN,199 999,10101.0,NaN,0.0,NaN,1,16v1
3,MN,1,301,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,12b,NaN,199 999,10101.0,NaN,0.0,NaN,4,16v1
4,MN,1,401,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,12b,NaN,1 99 999,10101.0,NaN,0.0,NaN,4,16v1

In [14]:
pluto_nyc.tail()

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,YCoord,ZoneMap,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,Version
124017,SI,8050,83,503,248.0,1016.0,31.0,51.0,10307.0,L076,...,124874.0,35a,NaN,505 532,53203.0,NaN,0.0,NaN,1,16v1
124018,SI,8050,86,503,248.0,1016.0,31.0,51.0,10307.0,L076,...,124805.0,35a,NaN,505 532,53203.0,NaN,0.0,NaN,1,16v1
124019,SI,8050,89,503,248.0,1016.0,31.0,51.0,10307.0,L076,...,124758.0,35a,NaN,505 532,53203.0,NaN,0.0,NaN,1,16v1
124020,SI,8050,92,503,248.0,1016.0,31.0,51.0,10307.0,L076,...,124743.0,35a,NaN,505 532,53203.0,NaN,0.0,NaN,1,16v1
124021,SI,8050,94,503,248.0,1016.0,31.0,51.0,10307.0,L076,...,124709.0,35a,NaN,505 532,53203.0,NaN,0.0,NaN,1,16v1

In [18]:
pluto_nyc.to_csv('../data/pluto/pluto_nyc.csv')